---
#- name: check whether we have joined this node
#  shell: "/usr/bin/docker ps | /bin/grep kube-proxy"
#  register: kube_proxy_running
#  ignore_errors: True

- name: update kubeadm template
  template:
    src: etc/kubernetes/kubeadm.conf
    dest: /etc/kubernetes/kubeadm.conf

# Note - always run this, updates kubeadm and kubelet config with any changes
# Note - would be nice to only do if kubeadm template has changed, but it always changes as it contains join token
- name: join nodes to masters by fqdn
  command: "/usr/bin/kubeadm join phase kubelet-start --config /etc/kubernetes/kubeadm.conf"
